# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc538ef08831ba6b1ad195a7d89e4c2173f8eb043020b3eb3c524a250463cead221bfc1ffd1cbe2bdc15319ebf8bfdd0572b5d904709d413f86d71e66fed78a9

test:
  secret_key_base: 3291bc2dffc4660eec2325e01404477fdb5c2c762a87623d092fb293a4ce68e07651f2dbc5dd9b3b25638928f5814450b975c4f9eddf99f5e1d09e6c86b68dc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
